import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { SessionProvider } from "next-auth/react"
import { Toaster } from "react-hot-toast";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const jetBrains = JetBrains_Mono({
  variable: "--font-jetbrain-mono",
  subsets: ["latin"],
});

import { Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${inter.variable} ${playfair.variable} ${jetBrains.variable} antialiased `}
      >

       <NextTopLoader color="orange"/>
        <SessionProvider>
          {children}
          <Toaster 
  position="bottom-right"
  reverseOrder={false}
  toastOptions={{
    style: {
      borderRadius: '10px',
      background: '#333',
      color: '#fff',
    },
  }}
/>
        </SessionProvider>
      </body>
    </html>
  );
}
